version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=govote
    - POSTGRES_USER=apigo
    - POSTGRES_PASSWORD=go-api
    ports:
    - "5432:5432"

volumes:
  db-data: {}